all:
  children:
    cluster1:
      children:
        master:
          hosts:
            pp1:
              ansible_host: 10.23.121.50
        workers:
          hosts:
            qg1:
              ansible_host: 10.23.121.11
            qg2:
              ansible_host: 10.23.121.12
      vars:
        cluster_name: flikweertintern121
  vars:
    ansible_user: root