all:
  children:
    cluster1:
      children:
        master:
          hosts:
            pp1:
              ansible_host: 10.23.40.50
        workers:
          hosts:
            qg1:
              ansible_host: 10.23.40.11
            qg2:
              ansible_host: 10.23.40.12
      vars:
        cluster_name: jonika
  vars:
    ansible_user: root
