all:
  children:
    cluster1:
      children:
        master:
          hosts:
            pp1:
              ansible_host: 10.23.36.50
        workers:
          hosts:
            qg1:
              ansible_host: 10.23.36.11
            qg2:
              ansible_host: 10.23.36.12
            qg3:
              ansible_host: 10.23.36.13
            qg4:
              ansible_host: 10.23.36.14
      vars:
        cluster_name: schuiling
  vars:
    ansible_user: root
