all:
  children:
    cluster1:
      children:
        master:
          hosts:
            pp1:
              ansible_host: 10.23.20.50
        workers:
          hosts:
            qg1:
              ansible_host: 10.23.20.11
            qg2:
              ansible_host: 10.23.20.12
      vars:
        cluster_name: bos
  vars:
    ansible_user: root
