all:
  children:
    cluster1:
      children:
        master:
          hosts:
            pp1:
              ansible_host: 10.23.30.50
        workers:
          hosts:
            qg1:
              ansible_host: 10.23.30.11
            qg2:
              ansible_host: 10.23.30.12
      vars:
        cluster_name: hack
  vars:
    ansible_user: root
