all:
  children:
    cluster1:
      children:
        master:
          hosts:
            pp1:
              ansible_host: 10.23.51.50
        workers:
          hosts:
            qg1:
              ansible_host: 10.23.51.11
            qg2:
              ansible_host: 10.23.51.12
      vars:
        cluster_name: debont
  vars:
    ansible_user: root
