all:
  children:
    cluster1:
      children:
        master:
          hosts:
            pp1:
              ansible_host: 10.23.252.50
        workers:
          hosts:
            qg1:
              ansible_host: 10.23.252.11
            qg2:
              ansible_host: 10.23.252.12
      vars:
        main_cluster_ip: 172.16.10.106
        cluster_name: 252-automatic
        cluster_version: v1.26.3+k3s1
        kube_env: test 
        kube_group: test-group
  vars:
    ansible_user: root