all:
  children:
    cluster1:
      children:
        master:
          hosts:
            pp1:
              ansible_host: 10.23.52.50
        workers:
          hosts:
            qg1:
              ansible_host: 10.23.52.11
            qg2:
              ansible_host: 10.23.52.12
            qg3:
              ansible_host: 10.23.52.13
            qg4:
              ansible_host: 10.23.52.14
      vars:
        main_cluster_ip: 172.16.10.105
        cluster_name: klaver
        cluster_version: v1.30.6+k3s1
        kube_env: dev
        kube_group: production
  vars:
    ansible_user: root
