all:
  children:
    cluster1:
      children:
        master:
          hosts:
            pp1:
              ansible_host: 10.23.106.50
        workers:
          hosts:
            qg1:
              ansible_host: 10.23.106.11
            qg2:
              ansible_host: 10.23.106.12
            qg3:
              ansible_host: 10.23.106.13
            qg4:
              ansible_host: 10.23.106.14
      vars:
        cluster_name: vdberge2
  vars:
    ansible_user: root
