all:
  children:
    cluster1:
      children:
        master:
          hosts:
            pp1:
              ansible_host: 10.23.252.50
        workers:
          hosts:
            qg1:
              ansible_host: 10.23.252.11
            qg2:
              ansible_host: 10.23.252.12
      vars:
        ansible_user: root
