- name: Fetch current cattle-cluster-agent deployment YAML
  command: >
    sudo k3s kubectl patch deployment cattle-cluster-agent -n cattle-system -p '{"spec":{"template":{"spec":{"dnsPolicy": "ClusterFirstWithHostNet", "hostNetwork": true}}}}'
  register: deployment_yaml

- name: Set nvidia runtime support
  shell: k3s kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v0.17.0/deployments/static/nvidia-device-plugin.yml

- name: Set dockerhub registration token
  shell: sudo k3s kubectl create secret docker-registry regcred --docker-server=https://index.docker.io/v1/ --docker-username=larsflikweert --docker-password={{ dockerhub_token }} --docker-email=lars@flikweertvision.nl

- name: Wait for 10 seconds to ensure components are ready
  wait_for:
    timeout: 10

- name: Label the node as a panel-pc node
  shell: sudo k3s kubectl label nodes $(hostname) --overwrite machine-type=PanelPC