- name: Test if the panel-pc can reach the main cluster
  ansible.builtin.command:
    cmd: "ping -c 2 {{ main_cluster_ip }}"
  register: ping_result
  failed_when: ping_result.rc != 0

- name: Editing the /etc/hosts file to make sure that we can reach the main cluster through 'rancher.flikweertvision.nl'
  lineinfile:
    path: /etc/hosts
    line: "{{ main_cluster_ip }} rancher.flikweertvision.nl"
    state: present
  become: true

- name: Set dynamic IP addresses
  ansible.builtin.set_fact:
    master_ip: "{{ ansible_default_ipv4.address }}"
    internal_ip: "{{ ansible_default_ipv4.address }}"
  when: ansible_default_ipv4 is defined