- name: Ensure rancher_url is set
  ansible.builtin.assert:
    that:
      - rancher_url is defined
      - rancher_url | length > 0
    fail_msg: "The variable 'rancher_url' is not set. (Check ./roles/panel_pc/vars/main.yml)"
    success_msg: "The variable 'rancher_url' is set."

- name: Ensure dockerhub_token is set
  ansible.builtin.assert:
    that:
      - dockerhub_token is defined
      - dockerhub_token | length > 0
    fail_msg: "The variable 'dockerhub_token' is not set. (Check ./roles/panel_pc/vars/main.yml)"
    success_msg: "The variable 'dockerhub_token' is set."

- name: Ensure main_cluster_pass is set
  ansible.builtin.assert:
    that:
      - main_cluster_pass is defined
      - main_cluster_pass | length > 0
    fail_msg: "The variable 'main_cluster_pass' is not set. (Check ./roles/panel_pc/vars/main.yml)"
    success_msg: "The variable 'main_cluster_pass' is set."

