- name: List ArgoCD applications
  shell: |
    sudo argocd app list
  delegate_to: "{{ main_cluster_ip }}"
  become: true
  register: argocd_app_list
  failed_when: argocd_app_list.rc != 0
  vars:
    ansible_user: fwv
    ansible_sudo_pass: "{{ main_cluster_pass }}"
  ignore_errors: true

- name: Fail if listing ArgoCD applications failed
  fail:
    msg: "{{main_cluster_ip}} has to relogin to ArgoCD, please do so by hand: 'sudo argocd login localhost:30503'"
  when: argocd_app_list.rc != 0