- name: Check available disk space on root partition
  ansible.builtin.command: df -h /
  register: disk_space

- name: Ensure at least 5GB of disk space is available
  ansible.builtin.assert:
    that:
      - disk_space.stdout | regex_search('\d+(?=G)') | int >= 5
    fail_msg: "Less than 5GB of disk space is available on the root partition."
    success_msg: "Sufficient disk space is available on the root partition."