# Install k3s on the panelPC and set the right labels
- name: Install a basic version of K3S (No rancher)
  shell: curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ cluster_version }} sh -

- name: Set NVIDIA runtime support for Docker
  shell: sudo k3s kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v0.17.0/deployments/static/nvidia-device-plugin.yml

- name: Set DockerHub registry token
  shell: sudo k3s kubectl create secret docker-registry regcred --docker-server=https://index.docker.io/v1/ --docker-username=larsflikweert --docker-password={{ dockerhub_token }} --docker-email=lars@flikweertvision.nl

- name: Label the current node as a PanelPC node
  shell: sudo k3s kubectl label nodes $(hostname) --overwrite machine-type=PanelPC