- name: Add NVIDIA GPG key
  shell: |
    curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
  args:
    creates: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg

- name: Add NVIDIA repository to APT sources
  shell: |
    curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
    sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
    tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
  args:
    creates: /etc/apt/sources.list.d/nvidia-container-toolkit.list

- name: Update APT cache
  apt:
    update_cache: yes
  
- name: nvidia-container-toolkit is installed
  apt:
    name: "nvidia-container-toolkit"
    state: present

- name: configure docker engine 1/2
  shell: sudo nvidia-ctk runtime configure --runtime=docker

- name: configure docker engine 2/2
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: |
      {
          "default-runtime": "nvidia",
          "runtimes": {
              "nvidia": {
                  "args": [],
                  "path": "nvidia-container-runtime"
              }
          }
      }
    owner: root
    group: root
    mode: '0644'


- name: Restart Docker engine
  systemd:
    name: docker.service
    state: restarted

- name: Wait for Docker to come back up
  pause:
    seconds: 10

- name: Join worker node to k3s cluster
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ cluster_version }} K3S_URL=https://{{ hostvars[groups['master'][0]]['ansible_host'] }}:6443 K3S_TOKEN={{ hostvars[groups['master'][0]]['k3s_token'] }} sh -s - --docker --node-label machine-type=QG