- name: Log in to Docker
  command: bash -c "echo '{{ dockerhub_token }}' | sudo docker login --username larsflikweert --password-stdin"
  become: true
  when: ansible_host == hostvars[groups['workers'][0]]['ansible_host']

- name: Pull Docker image
  command: sudo docker pull flikweertvision/quality_grader:{{ qg_tag }}
  become: true
  when: ansible_host == hostvars[groups['workers'][0]]['ansible_host']

- name: Save Docker image
  command: sudo docker save -o /tmp/quality_grader.tar flikweertvision/quality_grader:{{ qg_tag }}
  become: true
  when: ansible_host == hostvars[groups['workers'][0]]['ansible_host']

- name: From the other machines, sync the image
  command: sshpass -p "{{ machine_pass }}" scp root@{{ hostvars[groups['workers'][0]]['ansible_host'] }}:/tmp/quality_grader.tar /tmp/quality_grader.tar
  when: ansible_host != hostvars[groups['workers'][0]]['ansible_host']

- name: From the other machines, load the now downloaded image
  command: docker load -i /tmp/quality_grader.tar
  when: ansible_host != hostvars[groups['workers'][0]]['ansible_host']

- name: Delete the images on all the nodes
  command: rm /tmp/quality_grader.tar