- name: Check system health on master node
  hosts: master
  become: yes
  tasks:
    - name: PPC health check
      import_role: 
        name: panel_pc
        tasks_from: health_check

- name: Check system health on worker nodes
  hosts: workers
  become: yes
  tasks:
    - name: PC health check
      import_role: 
        name: quality_grader
        tasks_from: health_check

- name: Setup master node
  hosts: master
  gather_facts: true
  roles:
    - panel_pc

- name: Configure worker nodes with NVIDIA runtime and join cluster
  hosts: workers
  gather_facts: true
  roles:
    - quality_grader