---
- name: Verify connection to main cluster
  delegate_to: "{{ main_cluster_ip }}"
  shell: echo "Hello world!"

- name: Setup master node
  hosts: master
  gather_facts: true
  roles:
    - panel_pc

- name: Configure worker nodes with NVIDIA runtime and join cluster
  hosts: workers
  gather_facts: true
  roles:
    - quality_grader
