- name: Check system health on master node
  hosts: master
  become: yes
  tasks:
    - name: PPC health check
      import_role: 
        name: ppc_health_check
        tasks_from: variables
    - name: PPC connectivity check
      import_role: 
        name: ppc_health_check
        tasks_from: connectivity
    - name: PPC disk space check
      import_role: 
        name: ppc_health_check
        tasks_from: disk_space
    - name: PPC argocd check
      import_role: 
        name: ppc_health_check
        tasks_from: argocd_check
  vars_files:
    - vars/main.yml

- name: Check system health on worker nodes
  hosts: workers
  become: yes
  tasks:
    - name: PC health check
      import_role: 
        name: quality_grader
        tasks_from: health_check
  vars_files:
    - vars/main.yml

- name: Setup master node
  hosts: master
  gather_facts: true
  roles:
    - panel_pc
  vars_files:
    - vars/main.yml

- name: Configure worker nodes with NVIDIA runtime and join cluster
  hosts: workers
  gather_facts: true
  roles:
    - quality_grader
  vars_files:
    - vars/main.yml

- name: Install openkruise to the panelpc
  hosts: master
  become: yes
  tasks:
    - name: Install openkruise to the machine
      import_role: 
        name: panel_pc
        tasks_from: install_openkruise
  vars_files:
    - vars/main.yml