- name: Install openkruise to the panelpc
  hosts: master
  become: yes
  tasks:
    - name: Install openkruise to the machine
      import_role: 
        name: panel_pc
        tasks_from: install_openkruise