- name: Update openkruise deployment
  hosts: master
  become: true
  tasks:
    # - name: Uninstall openkruise since we want to upgrade it, but apparently upgrading doesn't work directly
    #   shell: |
    #     sudo helm --kubeconfig=/etc/rancher/k3s/k3s.yaml uninstall kruise

    # - name: Wait for openkruise to be uninstalled
    #   pause:
    #     seconds: 10

    - name: Update the openkruise deployment to specify the runtime socket path
      shell: |
        sudo helm --kubeconfig=/etc/rancher/k3s/k3s.yaml upgrade kruise openkruise/kruise --version 1.7.1 --set featureGates="ImagePullJobGate=true\,PreDownloadImageForDaemonSetUpdate=true\,TemplateNoDefaults=true" --set daemon.socketLocation=/var/run/k3s

- name: Symlink the cri-dockerd.sock file to the folder above (So openkruise can find it)
  hosts: workers
  become: true
  tasks: 
    - name: Symlink the cri-dockerd.sock file to the folder above
      shell: |
        cd /var/run/k3s && ln -s ./cri-dockerd/cri-dockerd.sock ./cri-dockerd.sock