- name: Check if all variables have been set
  hosts: localhost
  gather_facts: true
  roles:
    - pre_check
  vars_files:
    - vars/main.yml

- name: Check system health on PPC
  hosts: master
  become: yes
  roles:
    - panel_pc/health_check
  vars_files:
    - vars/main.yml

- name: Check system health on worker nodes
  hosts: workers
  become: yes
  tasks:
    - name: PC health check
      import_role: 
        name: quality_grader
        tasks_from: health_check
  vars_files:
    - vars/main.yml


- name: Pull image on main worker node
  hosts: workers
  gather_facts: true
  tasks:
    - name: Pull Docker images
      import_role: 
        name: quality_grader
        tasks_from: pre_pull
  vars_files:
    - vars/main.yml
    - vars/pre_pull.yml

- name: Pull images on main worker node
  hosts: master
  gather_facts: true
  roles:
    - panel_pc/pre_pull
  vars_files:
    - vars/main.yml
    - vars/pre_pull.yml
