- name: Check if all variables have been set
  hosts: localhost
  gather_facts: true
  roles:
    - pre_check
  vars_files:
    - vars/main.yml

- name: Check system health on master node
  hosts: master
  become: yes
  tasks:
    - name: PPC connectivity check
      import_role: 
        name: ppc_health_check
        tasks_from: connectivity
    - name: PPC disk space check
      import_role: 
        name: ppc_health_check
        tasks_from: disk_space
  vars_files:
    - vars/main.yml

- name: Check system health on worker nodes
  hosts: workers
  become: yes
  tasks:
    - name: PC health check
      import_role: 
        name: quality_grader
        tasks_from: health_check
  vars_files:
    - vars/main.yml


- name: Pull image on main worker node
  hosts: workers
  gather_facts: true
  tasks:
    - name: Pull Docker images
      import_role: 
        name: quality_grader
        tasks_from: pre_pull
  vars_files:
    - vars/main.yml

- name: Pull images on main worker node
  hosts: master
  gather_facts: true
  tasks:
    - name: Pull Docker images
      import_role: 
        name: panel_pc
        tasks_from: pre_pull
  vars_files:
    - vars/main.yml
