# - name: Check system health on master node
#   hosts: master
#   become: yes
#   tasks:
#     - name: PPC health check
#       import_role: 
#         name: panel_pc
#         tasks_from: health_check

- name: Check system health on worker nodes
  hosts: workers
  become: yes
  tasks:
    - name: PC health check
      import_role: 
        name: quality_grader
        tasks_from: health_check


- name: Pull image on main worker node
  hosts: workers
  gather_facts: true
  tasks:
    - name: Pull Docker images
      import_role: 
        name: quality_grader
        tasks_from: pre_pull

- name: Pull images on main worker node
  hosts: master
  gather_facts: true
  tasks:
    - name: Pull Docker images
      import_role: 
        name: panel_pc
        tasks_from: pre_pull
