- name: Check if all variables have been set
  hosts: localhost
  gather_facts: true
  roles:
    - pre_check
  vars_files:
    - vars/main.yml

- name: Check system health on PPC
  hosts: master
  become: yes
  roles:
    - panel_pc/health_check
  vars_files:
    - vars/main.yml

- name: Check system health on worker nodes
  hosts: workers
  become: yes
  roles:
    - quality_grader/health_check
  vars_files:
    - vars/main.yml

- name: Setup master node
  hosts: master
  gather_facts: true
  roles:
    - panel_pc/kubernetes_setup
  vars_files:
    - vars/main.yml

- name: Configure worker nodes with NVIDIA runtime and join cluster
  hosts: workers
  gather_facts: true
  roles:
    - quality_grader/kubernetes_setup
  vars_files:
    - vars/main.yml